version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/app
    depends_on:
      - mysql
      - php
  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/app
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - docker/.env
    volumes:
      - "./docker/volume/mysql:/var/lib/mysql"

  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/app
  artisan:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/app
    entrypoint: ["php", "/var/www/app/artisan"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    env_file:
      - docker/.env
